version: '3.8'
name: gym-management-golang-dev

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    image: gym-management-golang:dev
    container_name: gym-management-golang-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .dev.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    volumes:
      - ../../:/home/app/

  db:
    image: postgres:latest
    container_name: gym-management-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local