version: '3.8'
name: gym-management-api-gateway-golang-prod

services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    image: gym-management-api-gateway-golang:prod
    container_name: gym-management-api-gateway-golang-prod
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
