version: '3.8'
name: gym-management-api-gateway-golang-dev

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    image: gym-management-api-gateway-golang:dev
    container_name: gym-management-api-gateway-golang-dev
    ports:
      - "8080:8080"
    env_file:
      - ../../.env.dev
    volumes:
      - ../../:/home/app/
