apiVersion: v1
kind: PersistentVolume
metadata:
  name: gyms-service-psql-pv

spec:
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/gyms-service/psql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube