apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gyms-service-psql-pvc
  namespace: gyms-service-namespace

spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: gyms-service-psql-pv