apiVersion: v1
kind: Secret
metadata:
  name: gyms-service-secret
  namespace: gyms-service-namespace
data:
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  API_SECRET: "N2FmYTk2ZWM3YmRlOTZkYWY3ZDgxNjg3NDUzY2Q0ZWVmZDBjZTk0NWE0N2VhM2E2MDg5Yw=="
  RABBITMQ_URI: "YW1xcDovL3VzZXI6cGFzc3dvcmRAcmFiYml0bXEucmFiYml0bXEtbmFtZXNwYWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI="
