apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-discovery-redis-pv

spec:
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/yasser/Desktop/projects/lasting-dynamics/gym-management/data/service-discovery/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube