apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
  namespace: auth-service-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: yasserbelatreche/gym-management-auth-service:1.16
          env:
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: GIN_MODE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: DB_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: ADMIN_PASSWORD
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: RABBITMQ_URI
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: API_SECRET
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  namespace: auth-service-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080