apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-configmap
  namespace: auth-service-namespace
data:
    GIN_MODE: "release"
    DB_HOST: "auth-service-psql-service:5432"
    DB_NAME: "auth-service"
    DB_PORT: "5432"
