apiVersion: v1
kind: PersistentVolume
metadata:
  name: memberships-service-psql-pv

spec:
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/yasser/Desktop/projects/lasting-dynamics/gym-management/data/memberships-service/psql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube