apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memberships-service-psql-pvc

spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: memberships-service-psql-pv