name: Auth Service CI

on:
    push:
        branches:
            - 'deploy/microservices/auth-service'

defaults:
    run:
        working-directory: ./microservices/auth-service

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    IMAGE: ${{ secrets.DOCKER_USERNAME }}/gym-management-auth-service
    VERSION: 1.0.0

jobs:
    build-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.2
            - name: Install Dependencies
              run: go mod download && go mod verify
            - name: Setup Test Environment
              run: scripts/start-test.sh -d
            - name: Run Tests
              run: scripts/run-tests.sh

    dockerize:
        name: Dockerized and Push to Docker Hub
        runs-on: ubuntu-latest
        needs: build-test
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build The Image
              run: docker build . -f docker/prod/Dockerfile -t ${{ env.IMAGE }}:${{ env.VERSION }}
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}
            - name: Push The current version To Docker Hub
              run: docker push ${{ env.IMAGE }}:${{ env.VERSION }}
            - name: Update latest tag
              run: docker tag ${{ env.IMAGE }}:${{ env.VERSION }} ${{ env.IMAGE }}:latest
            - name: Push latest tag to Docker Hub
              run: docker push ${{ env.IMAGE }}:latest
